# Generated by Django 4.1.4 on 2023-01-07 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
                ('account_no', models.IntegerField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('Checking', 'Checking Account'), ('Savings', 'Savings Account '), ('MMAs', 'Money Market Account'), ('FDR', 'Fixed Deposit Account'), ('RD/DPS', 'Recurring Deposit Account'), ('CDs', 'Certificate of Deposit Account')], max_length=10)),
                ('non_expenditure_account', models.BooleanField()),
                ('custodial_name', models.CharField(max_length=20)),
                ('account_balance', models.FloatField(default=0.0)),
                ('opening_date', models.DateField(default=datetime.date.today)),
                ('last_update_date', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
