# Generated by Django 4.1.4 on 2023-01-11 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BAM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(choices=[('Checking', 'Checking Account'), ('Savings', 'Savings Account '), ('BO', 'Beneficiary Owners Account'), ('FDR', 'Fixed Deposit Account'), ('RD/DPS', 'Recurring Deposit Account'), ('CDs', 'Certificate of Deposit Account')], max_length=10),
        ),
        migrations.CreateModel(
            name='InterAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('details', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='BAM.accounts')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='BAM.accounts')),
            ],
        ),
    ]
