# Generated by Django 4.1.4 on 2022-12-25 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_accounts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
