# Generated by Django 4.1.4 on 2022-12-30 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_transaction_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('T', 'Transfer')], max_length=1)),
                ('ammount', models.FloatField()),
                ('transaction_summary', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='InterAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('details', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='accounts.accounts')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='accounts.accounts')),
            ],
        ),
        migrations.DeleteModel(
            name='Account_Transaction',
        ),
    ]
